### ISSUE TITLE
Add comparison of data between different demographic/geographical layers

### ISSUE THREAD

**Issue by enzoggqs** [gpmc-lab-ufrgs/atlas#100]
## Description
Add the possibility to compare data from different layers

## Tasks
- [ ] Analyze the code and check what is needed to do this
- [ ] Develop this new way to compare data

## Acceptance criteria
- [ ] Be possible to compare data from different layers
