### ISSUE TITLE
Handle zip code preview when in city layers

### ISSUE THREAD

**Issue by enzoggqs** [gpmc-lab-ufrgs/atlas#101]
## Description
As with the Australian version(https://opportunity.mit.edu/), the number of zip codes for a city should be displayed when in the city layer.

## Tasks
- [ ] Check how the current version works with Zip Codes
- [ ] Add the Zip Code count to each city
- [ ] Add the right position of each zip code in the city
