### ISSUE TITLE
Create functionality to analyze a specific radius

### ISSUE THREAD

**Issue by enzoggqs** [gpmc-lab-ufrgs/atlas#102]
## Description
Add new functionality that handles analysis of a specific area

## Tasks
- [ ] Study how to implement the functionality
- [ ] Prototype how would it be on the app
- [ ] Implement the functionality
