### ISSUE TITLE
Create backend to Brazil Atlas

### ISSUE THREAD

**Issue by LeoSilvaGomes** [gpmc-lab-ufrgs/atlas#106]
## Description
Since we already have a backend created by SA Atlas and GCES team (2022.1). We decided to verify if these application is worth to be used in our project.

## Tasks
- [x] Validate GCES backend application (@valdersonjr )
- [x] Validate SA atlas backend application (@AnaBeatrizPontes )
     - [x] Verify database from ufrgs (@valdersonjr )
- [x] Draw a diagram to describe the backend flow (C4) (@AnaBeatrizPontes )
- [ ] Create a documentation about each url (@enzoggqs )
- [x] Create a backend repository (@LeoSilvaGomes )

## Links
https://github.com/CxSci/SA-dashboard/tree/master/backend

**Comment by LeoSilvaGomes** [comment]
@AnaBeatrizPontes @enzoggqs please update the task description with the allocated between you

**Comment by valdersonjr** [comment]
> 

teste

**Comment by valdersonjr** [comment]
> @valdersonjr following the @gpmc-ufrgs instructions. you should create a message explaining **what/why** we want from UFRGS infrastructure! Please let me know if you need any help with that

I dont really know if there is a big difference between the utilization of MySQL or PostgresSQL. The thing is that GCES was using a extension that seemed to treat geospatial data, and that is why I suggested the change to postgres.

**Comment by AnaBeatrizPontes** [comment]
Validate SA atlas backend application - It was decided that the Australian backend had the best framework to follow, modify and improve for creating the atlas backend. We will not replicate the backend but we will use it as a query for any similarities

**Comment by AnaBeatrizPontes** [comment]
Draw a diagram to describe the backend flow (C4)  - Drawing the C4 model from the backend has been deprecated as it was not needed at this time.
