### ISSUE TITLE
Create state sidebar 

### ISSUE THREAD

**Issue by LeoSilvaGomes** [gpmc-lab-ufrgs/atlas#108]
## Description
Since we have the sidebar for the district layer, we decided to have the same behaviour for the state layer where we should show the specific data collected to this layer

## Tasks
- [ ] Create state layer structure
- [ ] Create data state structure
- [ ] Create behaviour to should sidebar at first click
- [ ] Create test for the sidebar
