### ISSUE TITLE
Spike | Add feature toggle to atlas using unleash

### ISSUE THREAD

**Issue by LeoSilvaGomes** [gpmc-lab-ufrgs/atlas#127]
## Description
One of the most popular ways to deliver a feature is using feature toggle to control bugs, version, ab test and release. Here in our project the feature toggle is one of the most important feature to start the revamp of some parts of atlas platform. 

This task include to understand how to integrate the feature toggle using unleash in our application and start the first steps (add config and some tests)

## Tasks
- [ ] Study about unleash
- [ ] Add what you learn about unleash in the comment
- [ ] Add the first steps in the platform
- [ ] Show a poc (as a video or in a call) about feature toggle
