### ISSUE TITLE
Graphic line to new data visualization

### ISSUE THREAD

**Issue by LeoSilvaGomes** [gpmc-lab-ufrgs/atlas#129]
## Description
Graphic line is a graphic to include a progressive data visualization and in our case won't be different, to be more specific we are thinking to use the graphic line to show the data at a time progression.

This visualization is a inherited from the SA Atlas that is already using the graphic line to timeline data.

## Tasks
- [ ] Add graphic line to the data at the sidebar
- [ ] Should follow the colors of the page
- [ ] Should fit the width size of the sidebar
- [ ] Make sure the graphic is following the SA atlas pattern
