### ISSUE TITLE
Integrate district layer with api

### ISSUE THREAD

**Issue by LeoSilvaGomes** [gpmc-lab-ufrgs/atlas#130]
## Description
Since we developed the backend to support the atlas data to the frontend, the next step is to integrate the endpoint already done in the backend part to the frontend

The main tool to be used in this development is the **axios**, and in the and of the task should deleted all the static data from the data folder in the frontend repository

## Tasks
- [ ] Create the config to connect the api with the front with axios
- [ ] Create class to support the api states to show
- [ ] Integrate class with district structure
- [ ] Connect with loading state and error state
- [ ] Provide the data to the district provider
- [ ] Delete static data from data folder

**Comment by k3vin-batista** [comment]
Hey, I already created the config but I'm a bit confused with how the map works. I tried to set the state 'all' on District provider but no sucess.
