### ISSUE TITLE
Integrate state layer with api

### ISSUE THREAD

**Issue by LeoSilvaGomes** [gpmc-lab-ufrgs/atlas#131]
## Description

Since we developed the backend to support the atlas data to the frontend, the next step is to integrate the endpoint already done in the backend part to the frontend

The main tool to be used in this development is the axios, and in the and of the task should deleted all the static data from the data folder in the frontend repository

## Tasks

- [ ] Create the config to connect the api with the front with axios
- [ ] Create class to support the api states to show
- [ ] Integrate class with state structure
- [ ] Connect with loading state and error state
- [ ] Provide the data to the state provider
- [ ] Delete static data from data folder

## Depends

**Comment by DouglasMonteles** [comment]
https://github.com/gpmc-lab-ufrgs/atlas/pull/154
