### ISSUE TITLE
Configure test library

### ISSUE THREAD

**Issue by LeoSilvaGomes** [gpmc-lab-ufrgs/atlas#46]
## Description

Create the settings to have test on our application, have same discussion with pattern 

## Tasks
- [ ] Install jest configs
- [ ] Install testing-library 
- [ ] Set a file-structure pattern for the tests

**Comment by twistershark** [comment]
The configuration was completed. The branch is updated with all the changes needed for the tests to be executed.

I made a change, not related to this issue, but to help improve the organization of the package.json. @types libs imported in the project aren't used when the application is built, so I moved them to devDependencies as they are only used in the dev environment.

I also needed to update the yarn.lock file because of these changes and the libs that were installed.
