### ISSUE TITLE
Add test to Collapsible component

### ISSUE THREAD

**Issue by LeoSilvaGomes** [gpmc-lab-ufrgs/atlas#47]
## Description

Thinking the problem to validate the quality of our application, this task came to create test cases for the **Collapsible** component

## Tasks
- [ ] Create test for different titles
- [ ] Create test with the component opened
- [ ] Create test for the component closed
- [ ] Create test for the content in the component

## Acceptance criteria
- [ ] 100% coverage
