### ISSUE TITLE
Add test to GridMode component

### ISSUE THREAD

**Issue by LeoSilvaGomes** [gpmc-lab-ufrgs/atlas#51]
## Description

Thinking the problem to validate the quality of our application, this task came to create test cases for the **GridMode** component

## Tasks
- [ ] Mock comparison data
- [ ] Mock section data
- [ ] Create test to verify if informations are showing

## Acceptance criteria
- [ ] 100% coverage
