### ISSUE TITLE
Add test to Header Component

### ISSUE THREAD

**Issue by enzoggqs** [gpmc-lab-ufrgs/atlas#53]
## Description
Thinking the problem to validate the quality of our application, this task came to create test cases for the **Header** component

## Tasks
- [ ] Create tests for different comparisonTypes
- [ ] Create test to error comparisonType
- [ ] Create test with isComparisonModeOn 
- [ ] Verify if functionality of SidebarOpen are working

## Acceptance criteria
- [ ] 100% coverage
