### ISSUE TITLE
Add test to InformationsBar component

### ISSUE THREAD

**Issue by enzoggqs** [gpmc-lab-ufrgs/atlas#54]
## Description
Thinking the problem to validate the quality of our application, this task came to create test cases for the **InformationsBar** component

## Tasks
- [ ] Mock sidebar provider
- [ ] Verify if `SummaryCard` show right informations
- [ ] Verify if `CloroplethLegend` show right text

## Acceptance criteria
- [ ] 100% coverage
