### ISSUE TITLE
Add test to LayerRoute component

### ISSUE THREAD

**Issue by LeoSilvaGomes** [gpmc-lab-ufrgs/atlas#57]
## Description
Thinking the problem to validate the quality of our application, this task came to create test cases for the **LayerRoute** component

## Tasks
- [ ] Mock Providers
- [ ] Verify visuation when district are selected
- [ ] Verify visualiton when state are selected
- [ ] Verify if resets are working
- [ ] Verify if back button are working
- [ ] Verify if router path show right layer names

## Acceptance criteria
- [ ] 100% coverage
