### ISSUE TITLE
Add test to MetricDetails component

### ISSUE THREAD

**Issue by LeoSilvaGomes** [gpmc-lab-ufrgs/atlas#59]
## Description
Thinking the problem to validate the quality of our application, this task came to create test cases for the **MetricDetails** component

## Tasks
- [ ] Mock district and metric values
- [ ] Verify if `Bar` visualization are showing right
- [ ] Verify default visualization

## Acceptance criteria
- [ ] 100% coverage
