### ISSUE TITLE
Add test to Modal component

### ISSUE THREAD

**Issue by LeoSilvaGomes** [gpmc-lab-ufrgs/atlas#60]
## Description
Thinking the problem to validate the quality of our application, this task came to create test cases for the **Modal** component

## Tasks
- [ ] Create spy to react-router
- [ ] Verify when click if path change and show modal
- [ ] Verify `AboutTheAtlas` content
- [ ] Verify `Contributors` content

## Acceptance criteria
- [ ] 100% coverage
