### ISSUE TITLE
Add test to SideBar component

### ISSUE THREAD

**Issue by LeoSilvaGomes** [gpmc-lab-ufrgs/atlas#63]
## Description
Thinking the problem to validate the quality of our application, this task came to create test cases for the **SideBar** component

## Tasks
- [ ] Mock sidebar provider
- [ ] Mock comparison provider
- [ ] Mock district provider
- [ ] Verify if title is showing

## Acceptance criteria
- [ ] 100% coverage
