### ISSUE TITLE
Add test to ComparisonDetails component

### ISSUE THREAD

**Issue by LeoSilvaGomes** [gpmc-lab-ufrgs/atlas#64]
## Description
Thinking the problem to validate the quality of our application, this task came to create test cases for the **ComparisonDetails** component

## Tasks
- [ ] Mock comparison provider
- [ ] Mock map provider
- [ ] Verify if informations are showing

## Acceptance criteria
- [ ] 100% coverage
