### ISSUE TITLE
Add explanation about the project on website

### ISSUE THREAD

**Issue by LeoSilvaGomes** [gpmc-lab-ufrgs/atlas#7]
## Description

On our website, we have two sidebars, one of them shows more details about the project: 
**About the Atlas:** Show the reason and result of the project
**About the Lab:** Show details about the laboratories involved in the project 
**Methods:** Show methods used on the project over the research
**Research:** Show results and progress of research around the project
**FAQ:** Common questions
**Contributors:** Show people involved in the project
In the other sidebar, we need a little resume about the project.

These options are a mirror of the SA atlas of opportunity. 

## Tasks
- [ ] Which topics to develop for BR atlas of opportunity
- [ ] Create the texts for each topic
- [ ] Available images for topics
