### ISSUE TITLE
Adjust issues found (Clean Code)

### ISSUE THREAD

**Issue by micaellagouveia** [gpmc-lab-ufrgs/atlas#81]
## Description
Following the instructions by GCES, the student need to find some structured problems in the platform by clean code methods.

## Tasks
- [x] ```customTypes```:
    - [x] Separate State and District interfaces and move them to a specific file.
    - [x] Change MapProps name for just Map.
- [x] ```store```: change folder name to a significant name, like ```contexts```
- [x] ```Map```:
    - [x] Move files used inside the component to a utils folder
    - [x] Remove sub components from components folder and leave just inside Map folder.
- [x] ```Footer```: move files used inside the component to a utils folder
- [x] ```Sidebar```: fix condition chaining
