### ISSUE TITLE
Geospatial Database

### ISSUE THREAD

**Issue by thiagolsg** [gpmc-lab-ufrgs/atlas#82]
## Description
Creating a geospatial database to replace the geojsons

## Tasks
- [x] Create container Postgis
- [x] ETL from json data to geospatial database
- [ ] Consume data from geospatial database
