### ISSUE TITLE
Create an adding data platform

### ISSUE THREAD

**Issue by AnaBeatrizPontes** [gpmc-lab-ufrgs/atlas#83]
## Description
Adding data to atlas is working manually at the moment, thinking about that a platform connected to atlas so that the data can be added more efficiently is needed

## Tasks
- [ ] Create the adding data platform flow (before development)
- [ ] Develop the adding data platform
- [ ] Connect the adding data platform with atlas

## Acceptance criteria
- [ ] Addition data platform flow be validated by data team and dev team
