### ISSUE TITLE
Create api to consume geospatial database

### ISSUE THREAD

**Issue by victordsantoss** [gpmc-lab-ufrgs/atlas#91]
## Description
The purpose of this issue is to create a REST Api using the NestJs framework to consume the PostgreSql database and reduce the memory consumption caused in the frontend.

### What is NestJs?
NestJS is a back-end framework that helps you develop efficient applications. scalable and reliable on top of Node.js. NestJS defaults to TypeScript and has an Angular-like syntax. By the way, NestJS also uses Express “under the hood”.

### Benefits of using NestJs:

- scalability
- facilitates api development
- facilitates the use of microservices architecture
- allows dynamic documentation creation
- organization (modularity)
- ease of implementing solid principles

Access the documentation clicking [here](https://nestjs.com/)!

## Tasks
- [x] Create api 
- [ ] Connect with database
- [ ] Implement tests using Jest
- [ ] Consume api in frontend
